eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: admin-server
logging: 
  file: "logs/boot-admin-sample.log"
management: 
  security: 
    enabled: false
boot: 
  admin: 
    routes: 
      endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream