server:
  port: 8762

spring:
  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zipkin: 
  base-url: http://localhost:9411
sleuth: 
  sampler: 
    percentage: 1.0
logging: 
  file: "logs/boot-admin-sample.log"
management: 
  security: 
    enabled: false